# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/howard/work/TinyThreadPool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/howard/work/TinyThreadPool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/howard/work/TinyThreadPool/CMakeFiles /home/howard/work/TinyThreadPool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/howard/work/TinyThreadPool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named men-client.app

# Build rule for target.
men-client.app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 men-client.app
.PHONY : men-client.app

# fast build rule for target.
men-client.app/fast:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/build
.PHONY : men-client.app/fast

#=============================================================================
# Target rules for targets named men-server.app

# Build rule for target.
men-server.app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 men-server.app
.PHONY : men-server.app

# fast build rule for target.
men-server.app/fast:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/build
.PHONY : men-server.app/fast

src/base/lockfreethreadpool.o: src/base/lockfreethreadpool.cc.o

.PHONY : src/base/lockfreethreadpool.o

# target to build an object file
src/base/lockfreethreadpool.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/base/lockfreethreadpool.cc.o
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/base/lockfreethreadpool.cc.o
.PHONY : src/base/lockfreethreadpool.cc.o

src/base/lockfreethreadpool.i: src/base/lockfreethreadpool.cc.i

.PHONY : src/base/lockfreethreadpool.i

# target to preprocess a source file
src/base/lockfreethreadpool.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/base/lockfreethreadpool.cc.i
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/base/lockfreethreadpool.cc.i
.PHONY : src/base/lockfreethreadpool.cc.i

src/base/lockfreethreadpool.s: src/base/lockfreethreadpool.cc.s

.PHONY : src/base/lockfreethreadpool.s

# target to generate assembly for a file
src/base/lockfreethreadpool.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/base/lockfreethreadpool.cc.s
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/base/lockfreethreadpool.cc.s
.PHONY : src/base/lockfreethreadpool.cc.s

src/base/thread.o: src/base/thread.cc.o

.PHONY : src/base/thread.o

# target to build an object file
src/base/thread.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/base/thread.cc.o
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/base/thread.cc.o
.PHONY : src/base/thread.cc.o

src/base/thread.i: src/base/thread.cc.i

.PHONY : src/base/thread.i

# target to preprocess a source file
src/base/thread.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/base/thread.cc.i
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/base/thread.cc.i
.PHONY : src/base/thread.cc.i

src/base/thread.s: src/base/thread.cc.s

.PHONY : src/base/thread.s

# target to generate assembly for a file
src/base/thread.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/base/thread.cc.s
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/base/thread.cc.s
.PHONY : src/base/thread.cc.s

src/base/threadpool.o: src/base/threadpool.cc.o

.PHONY : src/base/threadpool.o

# target to build an object file
src/base/threadpool.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/base/threadpool.cc.o
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/base/threadpool.cc.o
.PHONY : src/base/threadpool.cc.o

src/base/threadpool.i: src/base/threadpool.cc.i

.PHONY : src/base/threadpool.i

# target to preprocess a source file
src/base/threadpool.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/base/threadpool.cc.i
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/base/threadpool.cc.i
.PHONY : src/base/threadpool.cc.i

src/base/threadpool.s: src/base/threadpool.cc.s

.PHONY : src/base/threadpool.s

# target to generate assembly for a file
src/base/threadpool.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/base/threadpool.cc.s
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/base/threadpool.cc.s
.PHONY : src/base/threadpool.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/men-client/main.o: src/men-client/main.cc.o

.PHONY : src/men-client/main.o

# target to build an object file
src/men-client/main.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/men-client/main.cc.o
.PHONY : src/men-client/main.cc.o

src/men-client/main.i: src/men-client/main.cc.i

.PHONY : src/men-client/main.i

# target to preprocess a source file
src/men-client/main.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/men-client/main.cc.i
.PHONY : src/men-client/main.cc.i

src/men-client/main.s: src/men-client/main.cc.s

.PHONY : src/men-client/main.s

# target to generate assembly for a file
src/men-client/main.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/men-client/main.cc.s
.PHONY : src/men-client/main.cc.s

src/men-client/menclient.o: src/men-client/menclient.cc.o

.PHONY : src/men-client/menclient.o

# target to build an object file
src/men-client/menclient.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/men-client/menclient.cc.o
.PHONY : src/men-client/menclient.cc.o

src/men-client/menclient.i: src/men-client/menclient.cc.i

.PHONY : src/men-client/menclient.i

# target to preprocess a source file
src/men-client/menclient.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/men-client/menclient.cc.i
.PHONY : src/men-client/menclient.cc.i

src/men-client/menclient.s: src/men-client/menclient.cc.s

.PHONY : src/men-client/menclient.s

# target to generate assembly for a file
src/men-client/menclient.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/men-client/menclient.cc.s
.PHONY : src/men-client/menclient.cc.s

src/men/men.o: src/men/men.cc.o

.PHONY : src/men/men.o

# target to build an object file
src/men/men.cc.o:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/men/men.cc.o
.PHONY : src/men/men.cc.o

src/men/men.i: src/men/men.cc.i

.PHONY : src/men/men.i

# target to preprocess a source file
src/men/men.cc.i:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/men/men.cc.i
.PHONY : src/men/men.cc.i

src/men/men.s: src/men/men.cc.s

.PHONY : src/men/men.s

# target to generate assembly for a file
src/men/men.cc.s:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/men/men.cc.s
.PHONY : src/men/men.cc.s

src/men/redistool.o: src/men/redistool.cc.o

.PHONY : src/men/redistool.o

# target to build an object file
src/men/redistool.cc.o:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/men/redistool.cc.o
.PHONY : src/men/redistool.cc.o

src/men/redistool.i: src/men/redistool.cc.i

.PHONY : src/men/redistool.i

# target to preprocess a source file
src/men/redistool.cc.i:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/men/redistool.cc.i
.PHONY : src/men/redistool.cc.i

src/men/redistool.s: src/men/redistool.cc.s

.PHONY : src/men/redistool.s

# target to generate assembly for a file
src/men/redistool.cc.s:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/men/redistool.cc.s
.PHONY : src/men/redistool.cc.s

src/net/epolltool.o: src/net/epolltool.cc.o

.PHONY : src/net/epolltool.o

# target to build an object file
src/net/epolltool.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/epolltool.cc.o
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/epolltool.cc.o
.PHONY : src/net/epolltool.cc.o

src/net/epolltool.i: src/net/epolltool.cc.i

.PHONY : src/net/epolltool.i

# target to preprocess a source file
src/net/epolltool.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/epolltool.cc.i
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/epolltool.cc.i
.PHONY : src/net/epolltool.cc.i

src/net/epolltool.s: src/net/epolltool.cc.s

.PHONY : src/net/epolltool.s

# target to generate assembly for a file
src/net/epolltool.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/epolltool.cc.s
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/epolltool.cc.s
.PHONY : src/net/epolltool.cc.s

src/net/httpcontext.o: src/net/httpcontext.cc.o

.PHONY : src/net/httpcontext.o

# target to build an object file
src/net/httpcontext.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/httpcontext.cc.o
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/httpcontext.cc.o
.PHONY : src/net/httpcontext.cc.o

src/net/httpcontext.i: src/net/httpcontext.cc.i

.PHONY : src/net/httpcontext.i

# target to preprocess a source file
src/net/httpcontext.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/httpcontext.cc.i
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/httpcontext.cc.i
.PHONY : src/net/httpcontext.cc.i

src/net/httpcontext.s: src/net/httpcontext.cc.s

.PHONY : src/net/httpcontext.s

# target to generate assembly for a file
src/net/httpcontext.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/httpcontext.cc.s
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/httpcontext.cc.s
.PHONY : src/net/httpcontext.cc.s

src/net/httprequest.o: src/net/httprequest.cc.o

.PHONY : src/net/httprequest.o

# target to build an object file
src/net/httprequest.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/httprequest.cc.o
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/httprequest.cc.o
.PHONY : src/net/httprequest.cc.o

src/net/httprequest.i: src/net/httprequest.cc.i

.PHONY : src/net/httprequest.i

# target to preprocess a source file
src/net/httprequest.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/httprequest.cc.i
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/httprequest.cc.i
.PHONY : src/net/httprequest.cc.i

src/net/httprequest.s: src/net/httprequest.cc.s

.PHONY : src/net/httprequest.s

# target to generate assembly for a file
src/net/httprequest.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/httprequest.cc.s
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/httprequest.cc.s
.PHONY : src/net/httprequest.cc.s

src/net/httpserver.o: src/net/httpserver.cc.o

.PHONY : src/net/httpserver.o

# target to build an object file
src/net/httpserver.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/httpserver.cc.o
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/httpserver.cc.o
.PHONY : src/net/httpserver.cc.o

src/net/httpserver.i: src/net/httpserver.cc.i

.PHONY : src/net/httpserver.i

# target to preprocess a source file
src/net/httpserver.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/httpserver.cc.i
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/httpserver.cc.i
.PHONY : src/net/httpserver.cc.i

src/net/httpserver.s: src/net/httpserver.cc.s

.PHONY : src/net/httpserver.s

# target to generate assembly for a file
src/net/httpserver.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/httpserver.cc.s
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/httpserver.cc.s
.PHONY : src/net/httpserver.cc.s

src/net/libcurl.o: src/net/libcurl.cc.o

.PHONY : src/net/libcurl.o

# target to build an object file
src/net/libcurl.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/libcurl.cc.o
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/libcurl.cc.o
.PHONY : src/net/libcurl.cc.o

src/net/libcurl.i: src/net/libcurl.cc.i

.PHONY : src/net/libcurl.i

# target to preprocess a source file
src/net/libcurl.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/libcurl.cc.i
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/libcurl.cc.i
.PHONY : src/net/libcurl.cc.i

src/net/libcurl.s: src/net/libcurl.cc.s

.PHONY : src/net/libcurl.s

# target to generate assembly for a file
src/net/libcurl.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/libcurl.cc.s
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/libcurl.cc.s
.PHONY : src/net/libcurl.cc.s

src/net/sockettool.o: src/net/sockettool.cc.o

.PHONY : src/net/sockettool.o

# target to build an object file
src/net/sockettool.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/sockettool.cc.o
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/sockettool.cc.o
.PHONY : src/net/sockettool.cc.o

src/net/sockettool.i: src/net/sockettool.cc.i

.PHONY : src/net/sockettool.i

# target to preprocess a source file
src/net/sockettool.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/sockettool.cc.i
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/sockettool.cc.i
.PHONY : src/net/sockettool.cc.i

src/net/sockettool.s: src/net/sockettool.cc.s

.PHONY : src/net/sockettool.s

# target to generate assembly for a file
src/net/sockettool.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/sockettool.cc.s
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/sockettool.cc.s
.PHONY : src/net/sockettool.cc.s

src/net/tcpserver.o: src/net/tcpserver.cc.o

.PHONY : src/net/tcpserver.o

# target to build an object file
src/net/tcpserver.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/tcpserver.cc.o
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/tcpserver.cc.o
.PHONY : src/net/tcpserver.cc.o

src/net/tcpserver.i: src/net/tcpserver.cc.i

.PHONY : src/net/tcpserver.i

# target to preprocess a source file
src/net/tcpserver.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/tcpserver.cc.i
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/tcpserver.cc.i
.PHONY : src/net/tcpserver.cc.i

src/net/tcpserver.s: src/net/tcpserver.cc.s

.PHONY : src/net/tcpserver.s

# target to generate assembly for a file
src/net/tcpserver.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/tcpserver.cc.s
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/tcpserver.cc.s
.PHONY : src/net/tcpserver.cc.s

src/net/worker.o: src/net/worker.cc.o

.PHONY : src/net/worker.o

# target to build an object file
src/net/worker.cc.o:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/worker.cc.o
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/worker.cc.o
.PHONY : src/net/worker.cc.o

src/net/worker.i: src/net/worker.cc.i

.PHONY : src/net/worker.i

# target to preprocess a source file
src/net/worker.cc.i:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/worker.cc.i
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/worker.cc.i
.PHONY : src/net/worker.cc.i

src/net/worker.s: src/net/worker.cc.s

.PHONY : src/net/worker.s

# target to generate assembly for a file
src/net/worker.cc.s:
	$(MAKE) -f CMakeFiles/men-client.app.dir/build.make CMakeFiles/men-client.app.dir/src/net/worker.cc.s
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/net/worker.cc.s
.PHONY : src/net/worker.cc.s

src/test.o: src/test.cc.o

.PHONY : src/test.o

# target to build an object file
src/test.cc.o:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/test.cc.o
.PHONY : src/test.cc.o

src/test.i: src/test.cc.i

.PHONY : src/test.i

# target to preprocess a source file
src/test.cc.i:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/test.cc.i
.PHONY : src/test.cc.i

src/test.s: src/test.cc.s

.PHONY : src/test.s

# target to generate assembly for a file
src/test.cc.s:
	$(MAKE) -f CMakeFiles/men-server.app.dir/build.make CMakeFiles/men-server.app.dir/src/test.cc.s
.PHONY : src/test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... men-client.app"
	@echo "... men-server.app"
	@echo "... src/base/lockfreethreadpool.o"
	@echo "... src/base/lockfreethreadpool.i"
	@echo "... src/base/lockfreethreadpool.s"
	@echo "... src/base/thread.o"
	@echo "... src/base/thread.i"
	@echo "... src/base/thread.s"
	@echo "... src/base/threadpool.o"
	@echo "... src/base/threadpool.i"
	@echo "... src/base/threadpool.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/men-client/main.o"
	@echo "... src/men-client/main.i"
	@echo "... src/men-client/main.s"
	@echo "... src/men-client/menclient.o"
	@echo "... src/men-client/menclient.i"
	@echo "... src/men-client/menclient.s"
	@echo "... src/men/men.o"
	@echo "... src/men/men.i"
	@echo "... src/men/men.s"
	@echo "... src/men/redistool.o"
	@echo "... src/men/redistool.i"
	@echo "... src/men/redistool.s"
	@echo "... src/net/epolltool.o"
	@echo "... src/net/epolltool.i"
	@echo "... src/net/epolltool.s"
	@echo "... src/net/httpcontext.o"
	@echo "... src/net/httpcontext.i"
	@echo "... src/net/httpcontext.s"
	@echo "... src/net/httprequest.o"
	@echo "... src/net/httprequest.i"
	@echo "... src/net/httprequest.s"
	@echo "... src/net/httpserver.o"
	@echo "... src/net/httpserver.i"
	@echo "... src/net/httpserver.s"
	@echo "... src/net/libcurl.o"
	@echo "... src/net/libcurl.i"
	@echo "... src/net/libcurl.s"
	@echo "... src/net/sockettool.o"
	@echo "... src/net/sockettool.i"
	@echo "... src/net/sockettool.s"
	@echo "... src/net/tcpserver.o"
	@echo "... src/net/tcpserver.i"
	@echo "... src/net/tcpserver.s"
	@echo "... src/net/worker.o"
	@echo "... src/net/worker.i"
	@echo "... src/net/worker.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

