# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/howard/work/TinyThreadPool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/howard/work/TinyThreadPool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/howard/work/TinyThreadPool/CMakeFiles /home/howard/work/TinyThreadPool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/howard/work/TinyThreadPool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tinythreadpool.app

# Build rule for target.
tinythreadpool.app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinythreadpool.app
.PHONY : tinythreadpool.app

# fast build rule for target.
tinythreadpool.app/fast:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/build
.PHONY : tinythreadpool.app/fast

src/lockfreethreadpool.o: src/lockfreethreadpool.cc.o

.PHONY : src/lockfreethreadpool.o

# target to build an object file
src/lockfreethreadpool.cc.o:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/lockfreethreadpool.cc.o
.PHONY : src/lockfreethreadpool.cc.o

src/lockfreethreadpool.i: src/lockfreethreadpool.cc.i

.PHONY : src/lockfreethreadpool.i

# target to preprocess a source file
src/lockfreethreadpool.cc.i:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/lockfreethreadpool.cc.i
.PHONY : src/lockfreethreadpool.cc.i

src/lockfreethreadpool.s: src/lockfreethreadpool.cc.s

.PHONY : src/lockfreethreadpool.s

# target to generate assembly for a file
src/lockfreethreadpool.cc.s:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/lockfreethreadpool.cc.s
.PHONY : src/lockfreethreadpool.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/test.o: src/test.cc.o

.PHONY : src/test.o

# target to build an object file
src/test.cc.o:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/test.cc.o
.PHONY : src/test.cc.o

src/test.i: src/test.cc.i

.PHONY : src/test.i

# target to preprocess a source file
src/test.cc.i:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/test.cc.i
.PHONY : src/test.cc.i

src/test.s: src/test.cc.s

.PHONY : src/test.s

# target to generate assembly for a file
src/test.cc.s:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/test.cc.s
.PHONY : src/test.cc.s

src/threadpool.o: src/threadpool.cc.o

.PHONY : src/threadpool.o

# target to build an object file
src/threadpool.cc.o:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/threadpool.cc.o
.PHONY : src/threadpool.cc.o

src/threadpool.i: src/threadpool.cc.i

.PHONY : src/threadpool.i

# target to preprocess a source file
src/threadpool.cc.i:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/threadpool.cc.i
.PHONY : src/threadpool.cc.i

src/threadpool.s: src/threadpool.cc.s

.PHONY : src/threadpool.s

# target to generate assembly for a file
src/threadpool.cc.s:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/threadpool.cc.s
.PHONY : src/threadpool.cc.s

src/threadpooltest.o: src/threadpooltest.cc.o

.PHONY : src/threadpooltest.o

# target to build an object file
src/threadpooltest.cc.o:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/threadpooltest.cc.o
.PHONY : src/threadpooltest.cc.o

src/threadpooltest.i: src/threadpooltest.cc.i

.PHONY : src/threadpooltest.i

# target to preprocess a source file
src/threadpooltest.cc.i:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/threadpooltest.cc.i
.PHONY : src/threadpooltest.cc.i

src/threadpooltest.s: src/threadpooltest.cc.s

.PHONY : src/threadpooltest.s

# target to generate assembly for a file
src/threadpooltest.cc.s:
	$(MAKE) -f CMakeFiles/tinythreadpool.app.dir/build.make CMakeFiles/tinythreadpool.app.dir/src/threadpooltest.cc.s
.PHONY : src/threadpooltest.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... tinythreadpool.app"
	@echo "... edit_cache"
	@echo "... src/lockfreethreadpool.o"
	@echo "... src/lockfreethreadpool.i"
	@echo "... src/lockfreethreadpool.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
	@echo "... src/threadpool.o"
	@echo "... src/threadpool.i"
	@echo "... src/threadpool.s"
	@echo "... src/threadpooltest.o"
	@echo "... src/threadpooltest.i"
	@echo "... src/threadpooltest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

